### ISSUE TITLE
آموزش برای چندین سرور

### ISSUE THREAD

**Issue by AhooSaie** [iaghapour/IPV6-Tunnel#2]
سلام وقتتون بخیر باشه
اگه من بخوام از یک سرور ایران به چندین سرور خارج ipv6 لوکال بزنم باید چیکار کنم؟
چون طبق این فقط به یک سرور خارج رو متوجه شدم چطور انجام بدم.
ممنون

**Comment by MAhdioypu** [comment]
سلام سوال منم هست ممنون میشیم راهنمایی کنید

**Comment by iaghapour** [comment]
به زودی
